# Generated by Django 4.0.2 on 2022-10-13 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='photo',
            field=models.ImageField(default=1999, upload_to='photos/newsImg/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
