# Generated by Django 4.0.2 on 2022-10-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(default=1, upload_to='photos/users/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
